import { Account } from "./types/account";
import { Case } from "./types/case";
export const dummyUsers = [
  {
    id: "1",
    name: "Rayb",
  },
  {
    id: "2",
    name: "kutirng",
  },
  {
    id: "3",
    name: "jason",
  },
  {
    id: "4",
    name: "hentry",
  },
];

export const dummyAccounts: Account[] = [
  {
    id: "1",
    name: "Acme Corporation",
    tier: "Gold",
  },
  {
    id: "2",
    name: "Globex Corporation",
    tier: "Silver",
  },
  {
    id: "3",
    name: "Soylent Corp",
    tier: "Platinum",
  },
  {
    id: "4",
    name: "Initech",
    tier: "Basic",
  },
  {
    id: "5",
    name: "Vandelay Industries",
    tier: "Gold",
  },
  {
    id: "6",
    name: "Hooli",
    tier: "Silver",
  },
  {
    id: "7",
    name: "Pied Piper",
    tier: "Platinum",
  },
  {
    id: "8",
    name: "Bluth Company",
    tier: "Basic",
  },
  {
    id: "9",
    name: "Stark Industries",
    tier: "Gold",
  },
  {
    id: "10",
    name: "Wayne Enterprises",
    tier: "Platinum",
  },
  {
    id: "11",
    name: "Dunder Mifflin",
    tier: "Silver",
  },
  {
    id: "12",
    name: "Massive Dynamic",
    tier: "Gold",
  },
];
export const dummyCases: Case[] = [
  {
    id: "0000104",
    owner: dummyUsers[0],
    phone: "555-555-5555",
    email: "ltomlin@acme.biz",
    name: "Leanne Tomlin",
    account: dummyAccounts[0],
    status: "Open",
    priority: "High",
    type: "Incident",
    origin: "Email",
    reason: "Critical shipment delayed",
    notes:
      "Customer reports urgent delay in critical shipment. Immediate resolution needed to prevent business impact.",
    actions: [],
  },
  {
    id: "0000105",
    owner: dummyUsers[1],
    phone: "555-555-5555",
    email: "nmayer@globex.corp",
    name: "Nathan Mayer",
    account: dummyAccounts[1],
    status: "Open",
    priority: "Medium",
    type: "Question",
    origin: "Phone",
    reason: "Billing question",
    notes:
      "Customer queries recent charges and disputes bill amounts. Requires itemized billing explanation.",
    actions: [],
  },
  {
    id: "0000106",
    owner: dummyUsers[2],
    phone: "555-555-5555",
    email: "jwc@soylent.com",
    name: "John Crichton",
    account: dummyAccounts[2],
    status: "Closed",
    priority: "Low",
    type: "Request",
    origin: "Portal",
    reason: "Product return",
    notes:
      "Product returned, refund issued. Customer notified. No further action required.",
    actions: [],
  },
  {
    id: "0000107",
    owner: dummyUsers[3],
    phone: "555-555-5555",
    email: "linda@initech.dev",
    name: "Linda O'Conner",
    account: dummyAccounts[3],
    status: "Pending",
    priority: "Medium",
    type: "Request",
    origin: "Chat",
    reason: "Service request",
    notes:
      "Customer needs technical support for service issue. Ticket created, awaiting specialist assignment.",
    actions: [],
  },
  {
    id: "0000108",
    owner: dummyUsers[0],
    phone: "555-123-4567",
    email: "chris@vandelay.ind",
    name: "Chris P. Bacon",
    account: dummyAccounts[4],
    status: "Open",
    priority: "High",
    type: "Problem",
    origin: "Email",
    reason: "Login failure",
    notes: "Repeated login failures reported. Urgent fix required.",
    actions: [],
  },
  {
    id: "0000109",
    owner: dummyUsers[1],
    phone: "555-234-5678",
    email: "jane@hooli.xyz",
    name: "Jane Doe",
    account: dummyAccounts[5],
    status: "Pending",
    priority: "Low",
    type: "Request",
    origin: "Portal",
    reason: "Account upgrade",
    notes: "Requests account upgrade. Reviewing package options.",
    actions: [],
  },
  {
    id: "0000110",
    owner: dummyUsers[2],
    phone: "555-345-6789",
    email: "jack@piedpiper.com",
    name: "Jack Sparrow",
    account: dummyAccounts[6],
    status: "Closed",
    priority: "Medium",
    type: "Incident",
    origin: "Phone",
    reason: "Service outage",
    notes: "Reported service outage. Issue resolved, customer notified.",
    actions: [],
  },
  {
    id: "0000111",
    owner: dummyUsers[3],
    phone: "555-456-7890",
    email: "michael@bluthco.com",
    name: "Michael Bluth",
    account: dummyAccounts[7],
    status: "Open",
    priority: "Medium",
    type: "Question",
    origin: "Chat",
    reason: "Subscription renewal",
    notes: "Inquires about renewal discounts. Providing options.",
    actions: [],
  },
  {
    id: "0000112",
    owner: dummyUsers[0],
    phone: "555-567-8901",
    email: "tony@starkindustries.com",
    name: "Tony Stark",
    account: dummyAccounts[8],
    status: "Pending",
    priority: "High",
    type: "Problem",
    origin: "Email",
    reason: "Defective product",
    notes: "Reports defective product. Arranging replacement.",
    actions: [],
  },
  {
    id: "0000113",
    owner: dummyUsers[1],
    phone: "555-678-9012",
    email: "bruce@wayneenterprises.com",
    name: "Bruce Wayne",
    account: dummyAccounts[9],
    status: "Closed",
    priority: "Low",
    type: "Request",
    origin: "Portal",
    reason: "Information request",
    notes: "Sought information on product specs. Information provided.",
    actions: [],
  },
  {
    id: "0000114",
    owner: dummyUsers[2],
    phone: "555-789-0123",
    email: "pam@dundermifflin.com",
    name: "Pam Beesly",
    account: dummyAccounts[10],
    status: "Open",
    priority: "Medium",
    type: "Question",
    origin: "Phone",
    reason: "Order status",
    notes: "Checking on order status. Update provided.",
    actions: [],
  },
  {
    id: "0000115",
    owner: dummyUsers[3],
    phone: "555-890-1234",
    email: "walter@massivedynamic.com",
    name: "Walter Bishop",
    account: dummyAccounts[11],
    status: "Pending",
    priority: "High",
    type: "Incident",
    origin: "Chat",
    reason: "Unexpected charge",
    notes: "Disputes unexpected charge. Investigating issue.",
    actions: [],
  },
  {
    id: "0000116",
    owner: dummyUsers[0],
    phone: "555-901-2345",
    email: "elliot@ecorp.com",
    name: "Elliot Alderson",
    account: dummyAccounts[4],
    status: "Closed",
    priority: "Low",
    type: "Request",
    origin: "Email",
    reason: "Software update",
    notes: "Requested latest software update. Completed successfully.",
    actions: [],
  },
  {
    id: "0000117",
    owner: dummyUsers[1],
    phone: "555-012-3456",
    email: "liz@kabletown.com",
    name: "Liz Lemon",
    account: dummyAccounts[5],
    status: "Open",
    priority: "Medium",
    type: "Problem",
    origin: "Portal",
    reason: "Connectivity problems",
    notes: "Experiencing connectivity issues. Tech support engaged.",
    actions: [],
  },
];
